# -*- coding: utf-8 -*-
"""brain cancer mobilenetv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYYZ875aFpYjaYUW8Esum5IL_7KWeb4U
"""

!pip install visualkeras

!pip install kaggle

from google.colab import files
files.upload()

!mv "kaggle (1).json" kaggle.json

import os
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d orvile/brain-cancer-mri-dataset

import zipfile
with zipfile.ZipFile('brain-cancer-mri-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import visualkeras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
from google.colab import files
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.utils.class_weight import compute_class_weight

# ==============================
# 1. IMPORT LIBRARY
# ==============================
import os
import shutil
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# ==============================
# 2. PATH DATASET ASLI
# ==============================
base_dir = 'Brain_Cancer raw MRI data/Brain_Cancer'
output_dir = 'dataset_split'

# ==============================
# 3. BUAT FOLDER SPLIT
# ==============================
for split in ['train', 'val', 'test']:
    for cls in os.listdir(base_dir):
        os.makedirs(os.path.join(output_dir, split, cls), exist_ok=True)

# ==============================
# 4. SPLIT DATA (70:15:15)
# ==============================
for cls in os.listdir(base_dir):
    class_path = os.path.join(base_dir, cls)
    images = os.listdir(class_path)

    train, temp = train_test_split(images, test_size=0.3, random_state=42)
    val, test = train_test_split(temp, test_size=0.5, random_state=42)

    # copy file
    for img in train:
        shutil.copy(os.path.join(class_path, img),
                    os.path.join(output_dir, 'train', cls, img))

    for img in val:
        shutil.copy(os.path.join(class_path, img),
                    os.path.join(output_dir, 'val', cls, img))

    for img in test:
        shutil.copy(os.path.join(class_path, img),
                    os.path.join(output_dir, 'test', cls, img))

# ==============================
# 5. PATH BARU
# ==============================
train_dir = 'dataset_split/train'
val_dir   = 'dataset_split/val'
test_dir  = 'dataset_split/test'

# ==============================
# 6. IMAGE GENERATOR
# ==============================
train_datagen = ImageDataGenerator(
    rescale=1./255
)

val_test_datagen = ImageDataGenerator(
    rescale=1./255
)

# ==============================
# 7. LOAD DATA
# ==============================
train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='categorical',
    shuffle=True,
    seed=42
)

val_gen = val_test_datagen.flow_from_directory(
    val_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

test_gen = val_test_datagen.flow_from_directory(
    test_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

# ==============================
# 8. CEK JUMLAH DATA
# ==============================
print("Train:", train_gen.samples)
print("Validation:", val_gen.samples)
print("Test:", test_gen.samples)

# ==============================
# 9. CEK LABEL
# ==============================
print(train_gen.class_indices)

import os

for cls in os.listdir(train_dir):
    jumlah = len(os.listdir(os.path.join(train_dir, cls)))
    print(cls, ":", jumlah)

import matplotlib.pyplot as plt
import numpy as np

images, labels = next (train_gen)
plt.figure(figsize=(10, 10))
for i in range(6):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(images[i])
    plt.title(labels[i])
    plt.axis("off")

    plt.show()

print(train_gen.class_indices)

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

base_model.trainable = False
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)

# 🔥 WAJIB: output layer
predictions = Dense(3, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.summary()

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10
)

base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_fine = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=20
)

import matplotlib.pyplot as plt

# --- Akurasi ---
plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'], label='Train Accuracy', marker='o')
plt.plot(history.history['val_accuracy'], label='Val Accuracy', marker='o')
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

# --- Loss ---
plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Train Loss', marker='o')
plt.plot(history.history['val_loss'], label='Val Loss', marker='o')
plt.title('Training vs Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

# --- AUC ---
plt.figure(figsize=(8,5))
plt.plot(history.history['auc'], label='Train AUC', marker='o')
plt.plot(history.history['val_auc'], label='Val AUC', marker='o')
plt.title('Training vs Validation AUC')
plt.xlabel('Epoch')
plt.ylabel('AUC')
plt.legend()
plt.grid(True)
plt.show()

test_loss, test_acc = model.evaluate(test_gen)

print(f"Test Accuracy: {test_acc:.4f}")

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
# reset generator (penting biar urutan benar)
val_gen.reset()

# prediksi
y_pred = model.predict(val_gen)

# ambil kelas dengan probabilitas tertinggi
y_pred_classes = np.argmax(y_pred, axis=1)

# label asli
y_true = val_gen.classes

cm = confusion_matrix(y_true, y_pred_classes)
print(cm)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')

plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')

plt.show()

class_names = list(val_gen.class_indices.keys())
print(class_names)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

y_pred = model.predict(test_gen)
y_pred_classes = np.argmax(y_pred, axis=1)

y_true = test_gen.classes

print(classification_report(y_true, y_pred_classes, target_names=test_gen.class_indices.keys()))